version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: created_at
        tests: [not_null]
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: customer_name
        tests: [not_null]
  - name: stg_order_items
    columns:
      - name: order_id
        tests: [not_null]
      - name: sku
        tests: [not_null]
      - name: line_total
        tests: [not_null]
